### ISSUE TITLE
individual hazard rate

### ISSUE THREAD

**Issue by srn284** [havakv/pycox#106]
Hi @havakv,
I hope I find you well. It's an amazing package you have created here and I was wondering for the Nnet survival models (LogisticHazard), how can we calculate individualised hazard rate? 
Ultimately hoping to get some semblance of population wise hazard ratio (stratified by some variable X - e.g. hazard rates given X divided by hazard rates given ~X).

Thank you  in advance.
Warm wishes,
Shishir

**Comment by havakv** [comment]
Thank you for the kind words @srn284!

The `LogisticHazard` method should have a method called `predict_hazard` so you can use `model.predict_hazard(x)` to get the individual hazards. This should give you a matrix of estimated discrete hazard rates for each individual in `x` for each point in time.

Does this solve your problem?

**Comment by srn284** [comment]
Quite useful indeed! Thanks much!
