### ISSUE TITLE
Can't save or load model if path have a dot.

### ISSUE THREAD

**Issue by ruiite** [havakv/pycox#111]
Hi.
As title say if you have a dot in name of some folder in your path model will not save or load .
For get rid of this you just need to fix this lines in save_net and load_net :
`path_list = path.split('.')` to `path_list = os.path.splitext(path)`
and delete line : `extension = '.'+extension`

**Comment by havakv** [comment]
Thank you! For the record, I don't think it's a good idea to use a period in file paths, but I agree that the code shouldn't crash because of this. 
Made a PR #112
