### ISSUE TITLE
what is the function of gamma here

### ISSUE THREAD

**Issue by linzhlalala** [havakv/pycox#147]
the sub(gamma) and add(gamma) will finally eliminate each other in math. 

```
def cox_ph_loss_sorted(log_h: Tensor, events: Tensor, eps: float = 1e-7) -> Tensor: 
    if events.dtype is torch.bool:
        events = events.float()
    events = events.view(-1)
    log_h = log_h.view(-1)
    gamma = log_h.max()
    log_cumsum_h = log_h.sub(gamma).exp().cumsum(0).add(eps).log().add(gamma)
    return - log_h.sub(log_cumsum_h).mul(events).sum().div(events.sum())
```

**Comment by havakv** [comment]
This is numerical trick for ensuring that our floats doesn't overflow. While this is good practice in general, it's often critical when we're working with neural nets as we only have float32 precision. If you're interested you can read up on the log-sum-exp trick, but in short we're subtracting the max value `gamma` to ensure we're taking the exp of non-positive numbers (as exp of positive numbers get large very quickly), and adding it back later to get the correct result

**Comment by linzhlalala** [comment]
Thank you for answering. It is a clever solution.
