### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by qxzhong** [havakv/pycox#2]
Hi, 
When I carried out cox_models_1_introduction in examples file. I find that there are no metric and support datasets in datasets module. I was wondering how I could deal with such problem?
Looking forward your reply!

**Comment by havakv** [comment]
Hi, to circumvent licensing issues, we do not host any datasets directly in this repo, but instead download them as needed (they will then appear in your local "dataset" folder).
When running the following code
```python
from pycox import datasets
df = datasets.support.read_df()
```
it should download the `support` dataset and read it into python. The dataset should then appear in your local datasets folder.
You can alternatively call `datasets.support._download()` to explicitly download the dataset to the datasets folder.

If this does not solve your problem, please post the error you get when you try read the data frame into python.

**Comment by qxzhong** [comment]
I have fixed the problem. Thanks so much!
