### ISSUE TITLE
available models

### ISSUE THREAD

**Issue by gablum** [havakv/pycox#3]
Hi!
Is there any chance that also the deephit model for competing risks will be implemented in pycox? That would be great!

**Comment by havakv** [comment]
Hi!
We'll see if we can find the time, but it will probably not happen very soon.
In the meantime, you can take a look at the code by the deephit authors: 
https://github.com/chl8856/DeepHit 

Also, contributions are welcome!

**Comment by havakv** [comment]
I've now added a competing risks version of DeepHit, see #4

**Comment by gablum** [comment]
@havakv great! This is a very nice enhancement of available models in pycox!
