### ISSUE TITLE
metabric dataset doesn't load

### ISSUE THREAD

**Issue by ioannis12** [havakv/pycox#31]
when I run your introduction example the metabric dataset doesn't load. Is it a problem with the package?

**Comment by havakv** [comment]
Could you maybe post the error messages that you get?

**Comment by ioannis12** [comment]
sorry, I forgot it, 
it says it has to download it and then says:

 "ArrowInvalid: File is too small to be a well-formed file metabric"

It seems it's downloading from the /DeepSurv on github, the metabric_IHC4_clinical_train_test.h5 file, which is jus 90kb

**Comment by havakv** [comment]
So, I'm not immediately able to reproduce this error. 
Could you list the versions of feater-format and pyarrow? 
Also which os are you using? 
If you're conda or virtualenv, could you try a fresh environment to verify that there are no package dependencies that are causing the issue?

**Comment by ioannis12** [comment]
so I uninstalled and reinstalled anaconda, now I'm getting a different error message when I try to run metabric.read_df()

"ContextualVersionConflict: (numpy 1.13.3 (/Users/user2/anaconda3/lib/python3.6/site-packages), Requirement.parse('numpy>=1.14'), {'pyarrow'})"

pyarrow==0.16.0
feather-format==0.4.0
numpy==1.18.2

mac os 10.10.5

**Comment by havakv** [comment]
Hmm, everything there looks fine. When you reinstalled anaconda, there might have been some files left that breaks it. Could you try making a new environment and install everything there instead? The following should do it for you (create an environment called pycox_test, install pytorch, install pycox, and print the metabric data set:
```bash
conda create -n pycox_test python=3.6 -y
conda activate pycox_test
conda install pytorch torchvision -c pytorch -y
pip install pycox
python -c 'import pycox; print(pycox.datasets.metabric.read_df().head())'
```

**Comment by ioannis12** [comment]
yes, this is working, thank you!

I installed spyder on the new environment and I can run the introduction example file. 

cheers

**Comment by havakv** [comment]
Great to hear!
