### ISSUE TITLE
how to handle patient dropout?

### ISSUE THREAD

**Issue by ad05bzag** [havakv/pycox#32]
Hi, first of thank you so much for this great python package. I started with survival analysis only very recently, so your work and notebooks are absolutely godsend. My question might be silly though

I am wondering how to approach the dropout patients, ie patients that quit a study while still alive. I see that in the METABRIC dataset there does not seem to be a category like this, as there are only 0 and 1 in the event column. 

So, I was thinking that i could approach dropout patients as a competing risk problem? Does that make sense?

**Comment by havakv** [comment]
Hi, and thank you for the kind words!

So, I might misunderstand your question, but I think that what you are referring to as "dropout patients" (patients that quit the study while still alive) is typically called "censored obervations" or "censored survival times" in the survival literature. If that is the case, you don't need to consider competing risks, as censoring is a fundamental part of almost any survival model.

In the case of the metabric data set each observation has a "duration" and an "event" (see the [columns in the datset](https://nbviewer.jupyter.org/github/havakv/pycox/blob/master/examples/01_introduction.ipynb#Dataset)). The combination of the the "duration" and "event" tells you what happened to the patient. For example, if "duration" is 99 and "event" is 0, it means that the patient was censored at time 99 (he dropped out of the study while still alive at time 99). On the other hand, if "duration" is 99 and "event" is 1, it means that the patient died at time 99. 

Does this answer you question?
