### ISSUE TITLE
Question about baseline hazard in cox.py

### ISSUE THREAD

**Issue by ragAgar** [havakv/pycox#38]
Hi, 

Thank you for sharing the great implementation. 

I have a short question about the baseline hazard estimated in ```cox.py```.
Is ```_compute_baseline_hazards``` function in ```_CoxPHBase``` is the Breslow estimator? 

Thank you!

**Comment by havakv** [comment]
Hi, and thank you for the kind words!

Yes, it is the Breslow estimator. It is documented [here](https://github.com/havakv/pycox/blob/master/pycox/models/cox.py#L63) (though I'm aware that the docs aren't really in the best format).

**Comment by ragAgar** [comment]
Oops, I overlooked. 

Thank you for quick response.
