### ISSUE TITLE
Error occurs with 'download_kkbox()' method from 'kkbox' dataset

### ISSUE THREAD

**Issue by teboozas** [havakv/pycox#42]
Hi,

I've just tried to download `kkbox` dataset with `download_kkbox()` method,
but `FileNotFoundError` occurs during during `Extracting 'train'...` step.

How can I handle this problem? Thank you

**Comment by havakv** [comment]
Hi,
What OS are you on (Window, Mac, Linux)?
Have you installed the package using pip or by pulling this repo?
Have you set the `PYCOX_DATA_DIR` environment variable?

Can you check the directory <pycox_path>/datasets/data/kkbox and list the files there?
The <pycox_path> can be found by running
```python
import pycox
pycox.__file__  # '/Users/teboozas/anaconda3/envs/some_env/lib/python3.8/site-packages/pycox/__init__.py'
```
and remove the `__init__.py` part. So I want to you list the content of a folder such as
`/Users/teboozas/anaconda3/envs/some_env/lib/python3.8/site-packages/pycox/datasets/data/kkbox` (if you're on a mac).
You should be seeing some *.7z files.

**Comment by havakv** [comment]
Closed due to lack of response

**Comment by daehwanahn** [comment]
Hi, havakv

I have the same issue.

My OS is windows and installed with pip.
I checked the path you suggested and 3 files (for training) were there.
But, I got the same problem during 'extracting train...'.

Do you have any idea about this?

Thank you
