### ISSUE TITLE
Getting risk scores

### ISSUE THREAD

**Issue by hgjlee** [havakv/pycox#52]
Thanks for making this library available. I'm currently trying to produce time-dependent AUCs for the available models. Is there a way to get the models to produce risk scores given features?

**Comment by havakv** [comment]
Hi!
The typical risk scores for `CoxPH` can be obtained with `model.predict(x)`. However, most of the other methods in pycox are not proporitional hazards models, in which case there is not an obvious way to define the risk scores.

We have previously discussed this topic in #33, so you might want to read though that and ask if anything is not clear. 
In summary, you would need to create you own risk scores based on the survival estimates, and your resulting time-dependent AUCs will depend on your choice of transformation.

If you already know how you want to define the risk scores (in relation to survival/hazard/pmf/pdf estimates), I can help you achieve that from the models.

**Comment by hgjlee** [comment]
Thank you for your clarification! It was very helpful.
