### ISSUE TITLE
Is 'entity embedding' implemented here?

### ISSUE THREAD

**Issue by LeeJunHyun** [havakv/pycox#62]
Hi again,

Thanks to your kind support, I could successfully load data and run some models.

I have one more question about data processing. 

In the [paper](https://jmlr.org/papers/volume20/18-424/18-424.pdf), categorical covariates are embedded by using entity embeddings.

>For the neural networks, we standardize the numerical covariates and encode the categorical covariates by entity embeddings (Guo and Berkhahn, 2016) half the size of the number of categories.

Could you please let me know how can I use 'entity embeddings' in this package (or torchtuples)?
(if there is an example code or documentation, it would be very helpful for me)
I found entity embedding code at [here](https://github.com/havakv/torchtuples/blob/master/torchtuples/practical.py#L87) and [here](https://github.com/havakv/torchtuples/blob/master/torchtuples/practical.py#L113), but don't have any idea how to combine the entity embedding with MLP (or CoxPH model) for the survival analysis dataframe.

Thanks.

**Comment by havakv** [comment]
Hi again,

In the notebook [02_introduction.ipynb](https://nbviewer.jupyter.org/github/havakv/pycox/blob/master/examples/02_introduction.ipynb) there is an example of how to fit a model in pycox using entityembeddings. The example considers the LogisticHazard model, but it shouldn't be much work changing the code to work with other survival models.

So, you can start with that, and let me know if you run into any problems.

**Comment by LeeJunHyun** [comment]
So nice!!!

I really appreciate your commitment and feedback.

Thanks!
