### ISSUE TITLE
Survival time predictions (with CoxCC) using medical images

### ISSUE THREAD

**Issue by aslitoj** [havakv/pycox#65]
Hello,

This issue is similar to my other post but this time I wanted to build a model which takes images and predicts overall survival time as continuous by using CoxCC (instead of LogisticHazards) and followed the model shown in this jupyter notebook [04_mnist_dataloaders_cnn.ipynb](https://nbviewer.jupyter.org/github/havakv/pycox/blob/master/examples/04_mnist_dataloaders_cnn.ipynb). However, I got the error below. I am using databatchloader by the way.

When I tried with CoxCC and fit the model with:

`callbacks = [tt.cb.EarlyStopping()] 
epochs = 100 
verbose = True 
model = CoxCC(net, tt.optim.Adam(0.01))
log = model.fit_dataloader(dl_train, epochs, callbacks, verbose, val_dataloader=dl_val)`  gave me this error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-70-be2f0f7f1015> in <module>()
----> 1 log = model.fit_dataloader(dl_train, epochs, callbacks, verbose, val_dataloader=dl_val)

/usr/local/anaconda/lib/python3.6/site-packages/torchtuples/base.py in fit_dataloader(self, dataloader, epochs, callbacks, verbose, metrics, val_dataloader)
    227                 if stop: break
    228                 self.optimizer.zero_grad()
--> 229                 self.batch_metrics = self.compute_metrics(data, self.metrics)
    230                 self.batch_loss = self.batch_metrics['loss']
    231                 self.batch_loss.backward()

/usr/local/anaconda/lib/python3.6/site-packages/pycox/models/cox_cc.py in compute_metrics(self, input, metrics)
     50             raise RuntimeError("All elements in input does not have the same length.")
     51         case, control = input # both are TupleTree
---> 52         input_all = tt.TupleTree((case,) + control).cat()
     53         g_all = self.net(*input_all)
     54         g_all = tt.tuplefy(g_all).split(batch_size).flatten()

/usr/local/anaconda/lib/python3.6/site-packages/torchtuples/tupletree.py in cat(self, dim)
    420     @docstring(cat)
    421     def cat(self, dim=0):
--> 422         return cat(self, dim)
    423 
    424     def reduce_nrec(self, func, initial=None):

/usr/local/anaconda/lib/python3.6/site-packages/torchtuples/tupletree.py in cat(seq, dim)
    202     """
    203     if not seq.shapes().apply(lambda x: x[1:]).all_equal():
--> 204         raise ValueError("Shapes of merged arrays need to be the same")
    205 
    206     type_ = seq.type()

ValueError: Shapes of merged arrays need to be the same

Could you please help me to understand how can I solve this issue?
I really appreciate any help.

Best regards,

Asli Y.

**Comment by havakv** [comment]
Hi!
CoxCC and CoxTime have very special dataloaders, so they behave a bit differently then the other models. If you can work with all the data in memory, the simplest way to continue is to concatenate all the train and test data and use the regular `model.fit` method
```python
train = tt.tuplefy([data for data in dl_train]).cat()
test = tt.tuplefy([data for data in dl_test]).cat()
log = model.fit(*train, batch_size, epochs, callbacks, verbose, val_data=test)
```
Does this work for you?

**Comment by aslitoj** [comment]
Hi!
Thanks a lot for your comment, it solved the issue I was facing with!
