### ISSUE TITLE
Predicting ranks

### ISSUE THREAD

**Issue by armaneshaghi** [havakv/pycox#67]
First, thank you for this very useful package and your open-source work. Second, is there a way to predict ranks directly? I can use `model.predict_surv_df(dataframe)` to predict a dataframe of risk of event for each chosen time point, but can this be converted to a rank for observations? Say rank 1 for the observation with the highest and so on, similar to `sksurv` package? One example could be `sksurv`'s Gradient boosting predict function, see [here](https://scikit-survival.readthedocs.io/en/latest/api/generated/sksurv.ensemble.GradientBoostingSurvivalAnalysis.html).

**Comment by havakv** [comment]
Thank you for the kind words @armaneshaghi!

The question you're asking might be answered in #52 or #33. If that is not the case, please let me know.
