### ISSUE TITLE
Having troubles with downloading FLCHAIN dataset

### ISSUE THREAD

**Issue by MrHuff** [havakv/pycox#81]
Hi!

Thank you for making this library, it's epic. 

Having an issue when trying to download the FLCHAIN dataset, it gives me 404 error. 

Thanks for the help!

Best regards,
Robert

**Comment by MrHuff** [comment]
Found the bug, you have to change the url link in 

`def download_from_rdatasets(package, name):
    datasets = (pd.read_csv("https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv")
                .loc[lambda x: x['Package'] == package].set_index('Item'))
    if not name in datasets.index:
        raise ValueError(f"Dataset {name} not found.")
    info = datasets.loc[name]
    url = info.CSV 
    return pd.read_csv(url), info`

to 

`
def download_from_rdatasets(package, name):
    datasets = (pd.read_csv("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/datasets.csv")
                .loc[lambda x: x['Package'] == package].set_index('Item'))
    if not name in datasets.index:
        raise ValueError(f"Dataset {name} not found.")
    info = datasets.loc[name]
    url = info.CSV 
    return pd.read_csv(url), info
`

**Comment by havakv** [comment]
Nice work! Do you want to make an PR for this, or should I just do it?

**Comment by MrHuff** [comment]
Please do it!
