### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [havakv/pycox#88]
Adding a conda recipe would make distribution simpler, especially in combination with packages that require C/C++ libraries.

I am happy to work on this, in addition to https://github.com/havakv/torchtuples/issues/20.

Cheers,
Sarthak

**Comment by sarthakpati** [comment]
Is there any way to remove `py7zr` as a dependency? It is causing major headache for the conda recipe, and is only used in a [single function](https://github.com/havakv/pycox/blob/master/pycox/datasets/from_kkbox.py#L160) in a dataset class.

**Comment by havakv** [comment]
A conda recipe would probably be useful!

**Comment by havakv** [comment]
The dependency `py7zr` is just used to unzip some files. I chose that one because it works on Mac/Linux/Windows, but there are likely alternatives that could be used instead. Do you know any python packages for unzipping 7z files that are not problematic for the conda recipe?

**Comment by sarthakpati** [comment]
Oh okay. If it is used to unzip files, I believe there are built-in python libraries for it. If you specifically need support for 7z files, we need to look at alternatives, because `py7zr` is an absolute pain to build for conda 😭

**Comment by havakv** [comment]
This is specifically for the 7z files in the kkbox dataset that is downloaded from kaggle. So an alternative would be the best approach. An alternative would be to prompt the user to install `py7zr` if he/she tries to download the kkbox dataset, but that is a bit more messy

**Comment by sarthakpati** [comment]
I agree. I am exploring the capability to add `py7zr` into conda-forge right now, and I am ready for its dependencies to be merged ([1](https://github.com/conda-forge/staged-recipes/pull/15512),[2](https://github.com/conda-forge/staged-recipes/pull/15513),[3](https://github.com/conda-forge/staged-recipes/pull/15514),[4](https://github.com/conda-forge/staged-recipes/pull/15515)). Anyway, I am also exploring alternatives and will keep you posted.

**Comment by havakv** [comment]
Awesome!

**Comment by sarthakpati** [comment]
Okay, this took a while because I needed to get **all** dependencies into conda, but it is ready!!! 😄

**Comment by havakv** [comment]
Nice! How did you circumvent the issues with `py7zr`?

**Comment by sarthakpati** [comment]
I added conda recipes for py7zr and **all** of its dependencies. It was a right on pain, but glad because it got pycox in.
